# Generated by Django 4.0.6 on 2022-07-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=200)),
                ('urun_fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('urun_desc', models.CharField(max_length=200)),
                ('urun_foto', models.CharField(max_length=200)),
            ],
        ),
    ]
