# Generated by Django 4.0.6 on 2022-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ordered',
            new_name='order',
        ),
    ]
