# Generated by Django 4.0.6 on 2022-07-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_ordered_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
    ]
