# Generated by Django 4.0.6 on 2022-07-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
