# Generated by Django 4.0.6 on 2022-07-19 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_cartitem_total_price_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_deneme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orderitem'),
        ),
    ]
