# Generated by Django 4.0.6 on 2022-07-19 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_remove_cartitem_item_deneme_orderitem_item_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_deneme',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_deneme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.orderitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Fiyat'),
        ),
    ]
