# Generated by Django 4.0.6 on 2022-07-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_item_cartitem_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='items',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='items',
            field=models.ManyToManyField(null=True, to='base.orderitem'),
        ),
    ]
