# Generated by Django 4.0.6 on 2022-07-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_footerurl_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footerurl',
            old_name='name',
            new_name='title',
        ),
    ]
