# Generated by Django 4.0.6 on 2022-07-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_ilesitim_address_ilesitim_email_ilesitim_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilesitim',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ilesitim',
            name='email',
        ),
    ]
