# Generated by Django 4.0.6 on 2022-07-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_ilesitim_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilesitim',
            name='field',
            field=models.CharField(max_length=300, null=True, verbose_name='Alan'),
        ),
        migrations.AlterField(
            model_name='ilesitim',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Name'),
        ),
    ]
