# Generated by Django 4.0.6 on 2022-07-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_rename_items_cart_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=25, max_digits=10, null=True, verbose_name='Total Fiyat'),
        ),
    ]
