# Generated by Django 4.0.6 on 2022-07-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_orderitem_cart_orderitem_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ordered_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ürün Fiyatı'),
        ),
    ]
