# Generated by Django 4.0.6 on 2022-07-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_remove_cart_cart_item_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_price',
        ),
    ]
