# Generated by Django 4.0.6 on 2022-07-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_products_urun_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='image',
            name='image_index',
            field=models.ImageField(default=1, max_length=200, upload_to='', verbose_name='Ürün Fotoğraf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ürün Fiyatı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slug',
            field=models.SlugField(default='mehmet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='title',
            field=models.CharField(default='mehmet', max_length=200, verbose_name='Ürün Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='urun_desc',
            field=models.CharField(default='sefdae', max_length=200, verbose_name='Ürün Açıklaması'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='urun_foto',
            field=models.ImageField(default='predator.jpeg', max_length=200, upload_to='', verbose_name='Index Foto'),
            preserve_default=False,
        ),
    ]
