# Generated by Django 4.0.6 on 2022-07-24 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_order_order_total_price_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Fiyat'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.categories'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='urun_desc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='urun_foto',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Index Foto'),
        ),
    ]
