# Generated by Django 4.0.6 on 2022-07-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_orderitem_total_price_alter_orderitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_index',
        ),
    ]
