# Generated by Django 4.0.6 on 2022-08-14 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_alter_cartitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_item_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item_detail', to='base.products'),
        ),
    ]
