# Generated by Django 4.0.6 on 2022-08-14 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_cart_cart_item_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item_details',
        ),
    ]
