# Generated by Django 4.0.6 on 2022-07-16 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_id',
        ),
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.BigIntegerField(default=1, verbose_name='Kategori id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='urun_adi',
            field=models.CharField(max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='urun_desc',
            field=models.CharField(max_length=200, verbose_name='Ürün Açıklaması'),
        ),
        migrations.AlterField(
            model_name='products',
            name='urun_fiyat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ürün Fiyatı'),
        ),
        migrations.AlterField(
            model_name='products',
            name='urun_foto',
            field=models.ImageField(max_length=200, upload_to='', verbose_name='Ürün Fotoğraf'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products')),
            ],
        ),
        migrations.CreateModel(
            name='cart_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('ordered', models.BooleanField(default=False)),
                ('urun_adet', models.BigIntegerField(default=1)),
                ('items', models.ManyToManyField(to='base.orderitem')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
