# Generated by Django 4.0.6 on 2022-07-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_items',
            name='ordered',
        ),
    ]
