# Generated by Django 4.0.6 on 2022-07-17 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_cart_items_ordered_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
    ]
