# Generated by Django 4.0.6 on 2022-07-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_orderitem_item_deneme_cartitem_item_deneme_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='item_deneme',
            new_name='item',
        ),
    ]
