# Generated by Django 4.0.6 on 2022-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_remove_cartitem_items_cartitem_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
