# Generated by Django 4.0.6 on 2022-07-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_footerurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerurl',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Adı'),
        ),
    ]
