# Generated by Django 4.0.6 on 2022-07-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_alter_ilesitim_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ilesitim',
            new_name='Iletisim',
        ),
    ]
