# Generated by Django 4.0.6 on 2022-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_footerurl_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerurl',
            name='deneme',
        ),
    ]
