# Generated by Django 4.0.6 on 2022-07-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0070_orderitem_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_item_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ürün Fiyatı'),
        ),
    ]
