# Generated by Django 4.0.6 on 2022-07-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_remove_cartitem_cart_item_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(max_length=200, upload_to='', verbose_name='Ürün Fotoğraf')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='urun_foto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.image'),
        ),
    ]
