# Generated by Django 4.0.6 on 2022-07-24 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_remove_products_urun_foto_products_urun_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='urun_foto',
        ),
    ]
