# Generated by Django 4.0.6 on 2022-08-14 13:20

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_remove_image_image_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CartItems', to='base.cart'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product_image',
            field=models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to='', verbose_name='Ürün Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='products',
            name='urun_foto',
            field=models.ImageField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/static/images'), upload_to='', verbose_name='Index Foto'),
        ),
    ]
