# Generated by Django 4.0.6 on 2022-07-19 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_cartitem_items_cartitem_item_deneme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='item_deneme',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_deneme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cartitem'),
        ),
    ]
