# Generated by Django 4.0.6 on 2022-07-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_ilesitim_iletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='hakkimizda',
            name='field',
            field=models.CharField(max_length=300, null=True, verbose_name='Alan'),
        ),
        migrations.AddField(
            model_name='hakkimizda',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Alan Adı'),
        ),
    ]
