# Generated by Django 4.0.6 on 2022-07-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_alter_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category_name',
        ),
    ]
