# Generated by Django 4.0.6 on 2022-07-21 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_cartitem_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_item',
        ),
    ]
