# Generated by Django 4.0.6 on 2022-07-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_order_order_item_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.cart'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
