# Generated by Django 4.0.6 on 2022-07-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_remove_orderitem_cart_item_cartitem_cart_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart_item_price',
        ),
    ]
